# Generated by Django 5.1.7 on 2025-04-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='attendence',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
