# Generated by Django 5.1.7 on 2025-04-03 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_student_attendence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
    ]
