# Generated by Django 5.1.7 on 2025-04-03 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_student_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
