# Generated by Django 5.1.7 on 2025-04-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='attendence',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
