# Generated by Django 5.1.7 on 2025-04-07 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='user_data',
        ),
    ]
